import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const packs = JSON.parse(readFileSync(join(root, 'warehouse', 'PACKS.json'), 'utf8'));

const compiled = packs.map((p) => {
  const dir = join(root, 'warehouse', p.slug);
  const textbook = readFileSync(join(dir, 'TEXTBOOK.md'), 'utf8');
  const links = readFileSync(join(dir, 'LINK_INDEX.md'), 'utf8');
  return { ...p, textbook, links };
});

const outWarehouse = join(root, 'src', 'data', 'warehouse_compiled.ts');
const outStacks = join(root, 'src', 'data', 'stacks_compiled.ts');
mkdirSync(dirname(outWarehouse), { recursive: true });

const body =
  '/* generated by scripts/compile_warehouse.mjs — do not hand-edit */\n' +
  'export interface StackPack {\n' +
  '  slug: string;\n' +
  '  dewey: string;\n' +
  '  title: string;\n' +
  '  category: string;\n' +
  '  keywords: string[];\n' +
  '  textbook: string;\n' +
  '  links: string;\n' +
  '}\n\n' +
  'export type WarehousePack = StackPack;\n\n' +
  'export const STACKS_PACKS: StackPack[] = ' +
  JSON.stringify(compiled, null, 2) +
  ';\n\n' +
  'export const WAREHOUSE_PACKS: WarehousePack[] = STACKS_PACKS;\n';

writeFileSync(outWarehouse, body, 'utf8');
writeFileSync(outStacks, body, 'utf8');
console.log(`compiled ${compiled.length} academic packs -> ${outWarehouse} & ${outStacks}`);
