import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const stacksDir = join(root, 'stacks');
const packs = JSON.parse(readFileSync(join(stacksDir, 'PACKS.json'), 'utf8'));

const compiled = packs.map((p) => {
  const dir = join(stacksDir, p.slug);
  const textbook = readFileSync(join(dir, 'TEXTBOOK.md'), 'utf8');
  const links = readFileSync(join(dir, 'LINK_INDEX.md'), 'utf8');
  return { ...p, textbook, links };
});

const outStacks = join(root, 'src', 'data', 'stacks_compiled.ts');
mkdirSync(dirname(outStacks), { recursive: true });

const body =
  '/* generated by scripts/compile_stacks.mjs — do not hand-edit */\n' +
  'export interface StackPack {\n' +
  '  slug: string;\n' +
  '  dewey: string;\n' +
  '  title: string;\n' +
  '  category: string;\n' +
  '  keywords: string[];\n' +
  '  textbook: string;\n' +
  '  links: string;\n' +
  '}\n\n' +
  'export const STACKS_PACKS: StackPack[] = ' +
  JSON.stringify(compiled, null, 2) +
  ';\n';

writeFileSync(outStacks, body, 'utf8');
console.log(`compiled ${compiled.length} academic packs from stacks -> ${outStacks}`);
