import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const stacksDir = join(root, 'stacks');
const packs = JSON.parse(readFileSync(join(stacksDir, 'PACKS.json'), 'utf8'));

function extractUnits(textbook, dewey, slug) {
  const units = [];
  const lines = textbook.split(/\r?\n/);
  let currentChapter = 'General';

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line.startsWith('## ')) {
      currentChapter = line.replace(/^##\s+/, '').trim();
      continue;
    }
    // Pattern 1: Bold bullet: - **topic**: comment or * **topic** — comment
    const bulletMatch = line.match(/^[-*]\s+\*\*([^*]+)\*\*[:—\-]\s+(.+)$/);
    if (bulletMatch) {
      units.push({
        topic: bulletMatch[1].trim(),
        comment: bulletMatch[2].trim(),
        dewey,
        chapter: currentChapter,
        slug
      });
      continue;
    }
    // Pattern 2: Progen topic : comment
    const progenMatch = line.match(/^([^:]{2,60}):\s+([A-Za-z0-9].+)$/);
    if (progenMatch && !line.startsWith('http') && !line.startsWith('#') && !line.startsWith('|')) {
      const top = progenMatch[1].trim();
      if (!top.includes('http') && top.split(/\s+/).length <= 6 && !/^\d+$/.test(top)) {
        units.push({
          topic: top,
          comment: progenMatch[2].trim(),
          dewey,
          chapter: currentChapter,
          slug
        });
      }
    }
  }
  return units;
}

const compiled = packs.map((p) => {
  const dir = join(stacksDir, p.slug);
  const textbook = readFileSync(join(dir, 'TEXTBOOK.md'), 'utf8');
  const links = readFileSync(join(dir, 'LINK_INDEX.md'), 'utf8');
  const units = extractUnits(textbook, p.dewey, p.slug);
  return { ...p, textbook, links, units };
});

const outStacks = join(root, 'src', 'data', 'stacks_compiled.ts');
mkdirSync(dirname(outStacks), { recursive: true });

const body =
  '/* generated by scripts/compile_stacks.mjs — do not hand-edit */\n' +
  'export interface StackUnit {\n' +
  '  topic: string;\n' +
  '  comment: string;\n' +
  '  dewey: string;\n' +
  '  chapter: string;\n' +
  '  slug: string;\n' +
  '}\n\n' +
  'export interface StackPack {\n' +
  '  slug: string;\n' +
  '  dewey: string;\n' +
  '  title: string;\n' +
  '  category: string;\n' +
  '  level?: string;\n' +
  '  floor_age?: number;\n' +
  '  keywords: string[];\n' +
  '  textbook: string;\n' +
  '  links: string;\n' +
  '  units?: StackUnit[];\n' +
  '}\n\n' +
  'export const STACKS_PACKS: StackPack[] = ' +
  JSON.stringify(compiled, null, 2) +
  ';\n';

writeFileSync(outStacks, body, 'utf8');
const totalUnits = compiled.reduce((acc, p) => acc + (p.units ? p.units.length : 0), 0);
console.log(`compiled ${compiled.length} academic packs, ${totalUnits} atomic units from stacks -> ${outStacks}`);
