topic : boolean satisfiability problem

comment : determines whether variable assignment exists satisfying given propositional formula in conjunctive normal form.

domain : computing/automated_theorem_proving

reference : door https://satassociation.org/ // ref chapter 17.1

topic : dpll algorithm

comment : searches propositional truth assignments via recursive branching, unit propagation, and chronological backtracking.

domain : computing/automated_theorem_proving

reference : door https://dl.acm.org/doi/10.1145/368273.368557 // ref chapter 17.1

topic : conflict driven clause learning

comment : accelerates satisfiability solving by analyzing conflict graphs, learning asserting clauses, and backjumping non-chronologically.

domain : computing/automated_theorem_proving

reference : door https://satassociation.org/ // ref chapter 17.1

topic : unit propagation

comment : forces immediate assignment of remaining unassigned literal whenever clause contains single unresolved variable.

domain : computing/automated_theorem_proving

reference : door https://satassociation.org/ // ref chapter 17.1

topic : two watched literals

comment : monitors exactly two unassigned literals per clause to detect unit propagation without traversing unchanged clauses.

domain : computing/automated_theorem_proving

reference : door https://dl.acm.org/doi/10.1145/378239.379017 // ref chapter 17.1

topic : first unique implication point

comment : identifies single dominator node in conflict implication graph to minimize learned asserting clause size.

domain : computing/automated_theorem_proving

reference : door https://satassociation.org/ // ref chapter 17.1

topic : robinson resolution principle

comment : combines instantiation, modus ponens, and syllogism into single refutation-complete first-order inference rule.

domain : computing/automated_theorem_proving

reference : door https://aarr.org/ // ref chapter 17.2

topic : first order unification

comment : computes most general unifier substituting terms for variables to make opposing atomic formulas syntactically identical.

domain : computing/automated_theorem_proving

reference : door https://link.springer.com/journal/10817 // ref chapter 17.2

topic : occurs check

comment : precludes assigning variables to compound terms containing identical variables to prevent infinite cyclic terms.

domain : computing/automated_theorem_proving

reference : door https://link.springer.com/journal/10817 // ref chapter 17.2

topic : skolemization

comment : eliminates existential quantifiers in prenex formulas by replacing variables with deterministic Skolem functions.

domain : computing/automated_theorem_proving

reference : door https://aarr.org/ // ref chapter 17.2

topic : dependent type theory

comment : parameterizes types by computational terms to enable formal expression of mathematical theorems as types.

domain : computing/automated_theorem_proving

reference : door https://leanprover-community.github.io/ // ref chapter 17.3

topic : interactive proof assistant

comment : couples high-level human tactic direction with mechanized micro-step logical validation.

domain : computing/automated_theorem_proving

reference : door https://coq.inria.fr/ // ref chapter 17.3

topic : lean proof assistant

comment : implements dependent type theory with inductive types and quotient types atop native execution kernel.

domain : computing/automated_theorem_proving

reference : door https://leanprover-community.github.io/ // ref chapter 17.3

topic : coq proof assistant

comment : formalizes mechanized mathematics using calculus of inductive constructions and constructive type theory.

domain : computing/automated_theorem_proving

reference : door https://coq.inria.fr/ // ref chapter 17.3

topic : de bruijn criterion

comment : mandates small independent trustworthy core kernel to verify proof terms generated by unverified elaboration tactics.

domain : computing/automated_theorem_proving

reference : door https://deepspec.org/ // ref chapter 17.4

topic : trusted computing base

comment : minimizes critical kernel code required for proof validation to preserve absolute logical soundness.

domain : computing/automated_theorem_proving

reference : door https://sel4.systems/ // ref chapter 17.4

topic : sel4 microkernel verification

comment : demonstrates machine-checked mathematical proof of functional correctness and memory isolation against formal specification.

domain : computing/automated_theorem_proving

reference : door https://sel4.systems/ // ref chapter 17.4
