/* generated by scripts/compile_courses.mjs — do not hand-edit */
export interface AnswerKey {
  qtype: "mc" | "multi" | "numeric" | "short";
  answer: string | number | string[];
  tolerance?: number;
}

export const ANSWER_KEYS: Record<string, AnswerKey> = {
  "m-u1-q1": {
    "qtype": "mc",
    "answer": "falsifiable"
  },
  "m-u1-q2": {
    "qtype": "mc",
    "answer": "unfalsifiable"
  },
  "m-u1-q3": {
    "qtype": "short",
    "answer": "paradigm"
  },
  "m-u1-q4": {
    "qtype": "mc",
    "answer": "copying the forms of science without the honesty"
  },
  "m-u1-q5": {
    "qtype": "mc",
    "answer": "say so and fetch the primary"
  },
  "m-u2-q1": {
    "qtype": "mc",
    "answer": "a measurable procedure"
  },
  "m-u2-q2": {
    "qtype": "short",
    "answer": "null"
  },
  "m-u2-q3": {
    "qtype": "mc",
    "answer": "rejecting a true null"
  },
  "m-u2-q4": {
    "qtype": "mc",
    "answer": "failing to reject a false null"
  },
  "m-u2-q5": {
    "qtype": "numeric",
    "answer": 0.05,
    "tolerance": 0.000001
  },
  "m-u3-q1": {
    "qtype": "mc",
    "answer": "balance unknown confounders in expectation"
  },
  "m-u3-q2": {
    "qtype": "mc",
    "answer": "comparison against the treatment"
  },
  "m-u3-q3": {
    "qtype": "short",
    "answer": "rct"
  },
  "m-u3-q4": {
    "qtype": "mc",
    "answer": "expectation bias in measurement"
  },
  "m-u3-q5": {
    "qtype": "mc",
    "answer": "random assignment"
  },
  "m-u4-q1": {
    "qtype": "mc",
    "answer": "repeat scatter"
  },
  "m-u4-q2": {
    "qtype": "mc",
    "answer": "closeness to the true value"
  },
  "m-u4-q3": {
    "qtype": "short",
    "answer": "gum"
  },
  "m-u4-q4": {
    "qtype": "mc",
    "answer": "incomplete"
  },
  "m-u4-q5": {
    "qtype": "numeric",
    "answer": 0.02,
    "tolerance": 0.000001
  },
  "m-mt-q1": {
    "qtype": "mc",
    "answer": "Popper"
  },
  "m-mt-q2": {
    "qtype": "short",
    "answer": "null"
  },
  "m-mt-q3": {
    "qtype": "mc",
    "answer": "false alarm"
  },
  "m-mt-q4": {
    "qtype": "mc",
    "answer": "known and unknown confounders in expectation"
  },
  "m-mt-q5": {
    "qtype": "mc",
    "answer": "precise, not accurate"
  },
  "m-mt-q6": {
    "qtype": "numeric",
    "answer": 0.01,
    "tolerance": 0.000001
  },
  "m-mt-q7": {
    "qtype": "mc",
    "answer": "say so and fetch primary"
  },
  "m-mt-q8": {
    "qtype": "short",
    "answer": "gum"
  },
  "m-u5-q1": {
    "qtype": "mc",
    "answer": "P(data as extreme | H0)"
  },
  "m-u5-q2": {
    "qtype": "mc",
    "answer": "a pre-set threshold was crossed, not “true”"
  },
  "m-u5-q3": {
    "qtype": "short",
    "answer": "effect"
  },
  "m-u5-q4": {
    "qtype": "mc",
    "answer": "chance of detecting a real effect"
  },
  "m-u5-q5": {
    "qtype": "numeric",
    "answer": 0.8,
    "tolerance": 0.000001
  },
  "m-u6-q1": {
    "qtype": "mc",
    "answer": "prior with likelihood to a posterior"
  },
  "m-u6-q2": {
    "qtype": "short",
    "answer": "likelihood"
  },
  "m-u6-q3": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "m-u6-q4": {
    "qtype": "mc",
    "answer": "it never updates"
  },
  "m-u6-q5": {
    "qtype": "mc",
    "answer": "Bayes factor"
  },
  "m-u7-q1": {
    "qtype": "mc",
    "answer": "does not prove cause"
  },
  "m-u7-q2": {
    "qtype": "short",
    "answer": "confounder"
  },
  "m-u7-q3": {
    "qtype": "mc",
    "answer": "directed acyclic graph"
  },
  "m-u7-q4": {
    "qtype": "mc",
    "answer": "open a biasing path"
  },
  "m-u7-q5": {
    "qtype": "mc",
    "answer": "random assignment"
  },
  "m-u8-q1": {
    "qtype": "mc",
    "answer": "whoever is handy, not a random draw"
  },
  "m-u8-q2": {
    "qtype": "short",
    "answer": "probability"
  },
  "m-u8-q3": {
    "qtype": "mc",
    "answer": "non-respondents differ on the thing you care about"
  },
  "m-u8-q4": {
    "qtype": "mc",
    "answer": "undisclosed flexibility (QRPs)"
  },
  "m-u8-q5": {
    "qtype": "mc",
    "answer": "the whole frame"
  },
  "m-fn-q1": {
    "qtype": "mc",
    "answer": "outside Popper’s test"
  },
  "m-fn-q2": {
    "qtype": "mc",
    "answer": "true"
  },
  "m-fn-q3": {
    "qtype": "short",
    "answer": "power"
  },
  "m-fn-q4": {
    "qtype": "mc",
    "answer": "common effect"
  },
  "m-fn-q5": {
    "qtype": "numeric",
    "answer": 0.9,
    "tolerance": 0.000001
  },
  "m-fn-q6": {
    "qtype": "mc",
    "answer": "uncertainty of measurement"
  },
  "m-fn-q7": {
    "qtype": "short",
    "answer": "rct"
  },
  "m-fn-q8": {
    "qtype": "mc",
    "answer": "QRPs"
  },
  "x-u1-q1": {
    "qtype": "mc",
    "answer": "a statement that is true or false"
  },
  "x-u1-q2": {
    "qtype": "short",
    "answer": "conjunction"
  },
  "x-u1-q3": {
    "qtype": "mc",
    "answer": "P true, Q false"
  },
  "x-u1-q4": {
    "qtype": "mc",
    "answer": "the negation of the claim"
  },
  "x-u1-q5": {
    "qtype": "mc",
    "answer": "for all"
  },
  "x-u2-q1": {
    "qtype": "short",
    "answer": "integers"
  },
  "x-u2-q2": {
    "qtype": "mc",
    "answer": "ratios of integers (denominator ≠ 0)"
  },
  "x-u2-q3": {
    "qtype": "numeric",
    "answer": 0,
    "tolerance": 0.000001
  },
  "x-u2-q4": {
    "qtype": "mc",
    "answer": "empty"
  },
  "x-u2-q5": {
    "qtype": "numeric",
    "answer": 8,
    "tolerance": 0.000001
  },
  "x-u3-q1": {
    "qtype": "mc",
    "answer": "addition and scalar multiplication"
  },
  "x-u3-q2": {
    "qtype": "numeric",
    "answer": 11,
    "tolerance": 0.000001
  },
  "x-u3-q3": {
    "qtype": "short",
    "answer": "eigen"
  },
  "x-u3-q4": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-u3-q5": {
    "qtype": "mc",
    "answer": "orthogonal"
  },
  "x-u4-q1": {
    "qtype": "mc",
    "answer": "1"
  },
  "x-u4-q2": {
    "qtype": "numeric",
    "answer": 0,
    "tolerance": 0.000001
  },
  "x-u4-q3": {
    "qtype": "mc",
    "answer": "lim = f(a)"
  },
  "x-u4-q4": {
    "qtype": "short",
    "answer": "epsilon"
  },
  "x-u4-q5": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-mt-q1": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "x-mt-q2": {
    "qtype": "numeric",
    "answer": 11,
    "tolerance": 0.000001
  },
  "x-mt-q3": {
    "qtype": "mc",
    "answer": "1"
  },
  "x-mt-q4": {
    "qtype": "short",
    "answer": "eigen"
  },
  "x-mt-q5": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-mt-q6": {
    "qtype": "mc",
    "answer": "P true Q false"
  },
  "x-mt-q7": {
    "qtype": "numeric",
    "answer": 0,
    "tolerance": 0.000001
  },
  "x-mt-q8": {
    "qtype": "mc",
    "answer": "0"
  },
  "x-u5-q1": {
    "qtype": "numeric",
    "answer": 12,
    "tolerance": 0.000001
  },
  "x-u5-q2": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-u5-q3": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-u5-q4": {
    "qtype": "mc",
    "answer": "inverses (under hypotheses)"
  },
  "x-u5-q5": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-u6-q1": {
    "qtype": "mc",
    "answer": "toward steepest increase"
  },
  "x-u6-q2": {
    "qtype": "short",
    "answer": "divergence"
  },
  "x-u6-q3": {
    "qtype": "mc",
    "answer": "a boundary line integral"
  },
  "x-u6-q4": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "x-u6-q5": {
    "qtype": "mc",
    "answer": "true"
  },
  "x-u7-q1": {
    "qtype": "mc",
    "answer": "exponentials"
  },
  "x-u7-q2": {
    "qtype": "numeric",
    "answer": 0,
    "tolerance": 0.000001
  },
  "x-u7-q3": {
    "qtype": "short",
    "answer": "characteristic"
  },
  "x-u7-q4": {
    "qtype": "mc",
    "answer": "PDE"
  },
  "x-u7-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "x-u8-q1": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "x-u8-q2": {
    "qtype": "mc",
    "answer": "prior with data"
  },
  "x-u8-q3": {
    "qtype": "short",
    "answer": "central"
  },
  "x-u8-q4": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-u8-q5": {
    "qtype": "mc",
    "answer": "P(A)P(B)"
  },
  "x-fn-q1": {
    "qtype": "numeric",
    "answer": 12,
    "tolerance": 0.000001
  },
  "x-fn-q2": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-fn-q3": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "x-fn-q4": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "x-fn-q5": {
    "qtype": "mc",
    "answer": "inverses under hypotheses"
  },
  "x-fn-q6": {
    "qtype": "short",
    "answer": "exponential"
  },
  "x-fn-q7": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "x-fn-q8": {
    "qtype": "mc",
    "answer": "1"
  },
  "p-u1-q1": {
    "qtype": "mc",
    "answer": "model that predicts measurements"
  },
  "p-u1-q2": {
    "qtype": "short",
    "answer": "second"
  },
  "p-u1-q3": {
    "qtype": "mc",
    "answer": "conservation laws"
  },
  "p-u1-q4": {
    "qtype": "mc",
    "answer": "not a cite"
  },
  "p-u1-q5": {
    "qtype": "numeric",
    "answer": 7,
    "tolerance": 0.000001
  },
  "p-u2-q1": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "p-u2-q2": {
    "qtype": "mc",
    "answer": "constant"
  },
  "p-u2-q3": {
    "qtype": "short",
    "answer": "equal and opposite"
  },
  "p-u2-q4": {
    "qtype": "numeric",
    "answer": 5,
    "tolerance": 0.000001
  },
  "p-u2-q5": {
    "qtype": "mc",
    "answer": "dv/dt"
  },
  "p-u3-q1": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "p-u3-q2": {
    "qtype": "mc",
    "answer": "path"
  },
  "p-u3-q3": {
    "qtype": "short",
    "answer": "kinetic"
  },
  "p-u3-q4": {
    "qtype": "numeric",
    "answer": 9,
    "tolerance": 0.000001
  },
  "p-u3-q5": {
    "qtype": "mc",
    "answer": "the system is isolated in the relevant sense"
  },
  "p-u4-q1": {
    "qtype": "mc",
    "answer": "r × F"
  },
  "p-u4-q2": {
    "qtype": "short",
    "answer": "angular"
  },
  "p-u4-q3": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "p-u4-q4": {
    "qtype": "mc",
    "answer": "angular momentum"
  },
  "p-u4-q5": {
    "qtype": "numeric",
    "answer": 8,
    "tolerance": 0.000001
  },
  "p-mt-q1": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "p-mt-q2": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "p-mt-q3": {
    "qtype": "numeric",
    "answer": 9,
    "tolerance": 0.000001
  },
  "p-mt-q4": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "p-mt-q5": {
    "qtype": "mc",
    "answer": "constant velocity"
  },
  "p-mt-q6": {
    "qtype": "short",
    "answer": "second"
  },
  "p-mt-q7": {
    "qtype": "numeric",
    "answer": 7,
    "tolerance": 0.000001
  },
  "p-mt-q8": {
    "qtype": "mc",
    "answer": "independent"
  },
  "p-u5-q1": {
    "qtype": "mc",
    "answer": "−kx"
  },
  "p-u5-q2": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "p-u5-q3": {
    "qtype": "short",
    "answer": "resonance"
  },
  "p-u5-q4": {
    "qtype": "mc",
    "answer": "energy"
  },
  "p-u5-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "p-u6-q1": {
    "qtype": "mc",
    "answer": "electricity, magnetism, light"
  },
  "p-u6-q2": {
    "qtype": "short",
    "answer": "light"
  },
  "p-u6-q3": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "p-u6-q4": {
    "qtype": "mc",
    "answer": "an electric field (Faraday)"
  },
  "p-u6-q5": {
    "qtype": "mc",
    "answer": "c"
  },
  "p-u7-q1": {
    "qtype": "mc",
    "answer": "thermal equilibrium / temperature"
  },
  "p-u7-q2": {
    "qtype": "short",
    "answer": "energy"
  },
  "p-u7-q3": {
    "qtype": "mc",
    "answer": "does not decrease"
  },
  "p-u7-q4": {
    "qtype": "numeric",
    "answer": -273,
    "tolerance": 0.000001
  },
  "p-u7-q5": {
    "qtype": "mc",
    "answer": "log of microstate count"
  },
  "p-u8-q1": {
    "qtype": "mc",
    "answer": "hf"
  },
  "p-u8-q2": {
    "qtype": "short",
    "answer": "wave"
  },
  "p-u8-q3": {
    "qtype": "mc",
    "answer": "x and p"
  },
  "p-u8-q4": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "p-u8-q5": {
    "qtype": "mc",
    "answer": "NIST CODATA"
  },
  "p-fn-q1": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "p-fn-q2": {
    "qtype": "numeric",
    "answer": 9,
    "tolerance": 0.000001
  },
  "p-fn-q3": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "p-fn-q4": {
    "qtype": "mc",
    "answer": "c"
  },
  "p-fn-q5": {
    "qtype": "short",
    "answer": "energy"
  },
  "p-fn-q6": {
    "qtype": "mc",
    "answer": "-kx"
  },
  "p-fn-q7": {
    "qtype": "numeric",
    "answer": 7,
    "tolerance": 0.000001
  },
  "p-fn-q8": {
    "qtype": "mc",
    "answer": "hf"
  },
  "c-u1-q1": {
    "qtype": "mc",
    "answer": "atoms"
  },
  "c-u1-q2": {
    "qtype": "short",
    "answer": "electrons"
  },
  "c-u1-q3": {
    "qtype": "mc",
    "answer": "atoms into new substances"
  },
  "c-u1-q4": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "c-u1-q5": {
    "qtype": "mc",
    "answer": "IUPAC"
  },
  "c-u2-q1": {
    "qtype": "mc",
    "answer": "proton count"
  },
  "c-u2-q2": {
    "qtype": "short",
    "answer": "isotopes"
  },
  "c-u2-q3": {
    "qtype": "mc",
    "answer": "noble-gas stability"
  },
  "c-u2-q4": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "c-u2-q5": {
    "qtype": "mc",
    "answer": "CIAAW"
  },
  "c-u3-q1": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-u3-q2": {
    "qtype": "short",
    "answer": "mole"
  },
  "c-u3-q3": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "c-u3-q4": {
    "qtype": "mc",
    "answer": "moles of solute"
  },
  "c-u3-q5": {
    "qtype": "numeric",
    "answer": 0.4,
    "tolerance": 0.000001
  },
  "c-u4-q1": {
    "qtype": "mc",
    "answer": "electron transfer and electrostatics"
  },
  "c-u4-q2": {
    "qtype": "short",
    "answer": "covalent"
  },
  "c-u4-q3": {
    "qtype": "mc",
    "answer": "shape from electron domains"
  },
  "c-u4-q4": {
    "qtype": "mc",
    "answer": "two bonds + two lone pairs on O"
  },
  "c-u4-q5": {
    "qtype": "numeric",
    "answer": 4,
    "tolerance": 0.000001
  },
  "c-mt-q1": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "c-mt-q2": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-mt-q3": {
    "qtype": "numeric",
    "answer": 0.4,
    "tolerance": 0.000001
  },
  "c-mt-q4": {
    "qtype": "short",
    "answer": "isotopes"
  },
  "c-mt-q5": {
    "qtype": "mc",
    "answer": "shared pairs"
  },
  "c-mt-q6": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "c-mt-q7": {
    "qtype": "short",
    "answer": "mole"
  },
  "c-mt-q8": {
    "qtype": "mc",
    "answer": "shape"
  },
  "c-u5-q1": {
    "qtype": "mc",
    "answer": "atoms of each element"
  },
  "c-u5-q2": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-u5-q3": {
    "qtype": "short",
    "answer": "limiting"
  },
  "c-u5-q4": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "c-u5-q5": {
    "qtype": "mc",
    "answer": "mole ratios"
  },
  "c-u6-q1": {
    "qtype": "mc",
    "answer": "PV = nRT"
  },
  "c-u6-q2": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "c-u6-q3": {
    "qtype": "short",
    "answer": "partial"
  },
  "c-u6-q4": {
    "qtype": "mc",
    "answer": "high P / low T"
  },
  "c-u6-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-u7-q1": {
    "qtype": "mc",
    "answer": "exothermic"
  },
  "c-u7-q2": {
    "qtype": "short",
    "answer": "g"
  },
  "c-u7-q3": {
    "qtype": "mc",
    "answer": "how fast"
  },
  "c-u7-q4": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-u7-q5": {
    "qtype": "mc",
    "answer": "NIST WebBook"
  },
  "c-u8-q1": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "c-u8-q2": {
    "qtype": "short",
    "answer": "autoionization"
  },
  "c-u8-q3": {
    "qtype": "mc",
    "answer": "pH change"
  },
  "c-u8-q4": {
    "qtype": "mc",
    "answer": "toward reactants"
  },
  "c-u8-q5": {
    "qtype": "numeric",
    "answer": 7,
    "tolerance": 0.000001
  },
  "c-fn-q1": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-fn-q2": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "c-fn-q3": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "c-fn-q4": {
    "qtype": "short",
    "answer": "limiting"
  },
  "c-fn-q5": {
    "qtype": "mc",
    "answer": "ideal gas"
  },
  "c-fn-q6": {
    "qtype": "numeric",
    "answer": 6,
    "tolerance": 0.000001
  },
  "c-fn-q7": {
    "qtype": "mc",
    "answer": "exothermic"
  },
  "c-fn-q8": {
    "qtype": "numeric",
    "answer": 7,
    "tolerance": 0.000001
  },
  "b-u1-q1": {
    "qtype": "mc",
    "answer": "coupling to energy flows and keeping order locally"
  },
  "b-u1-q2": {
    "qtype": "short",
    "answer": "unit"
  },
  "b-u1-q3": {
    "qtype": "mc",
    "answer": "at higher scales"
  },
  "b-u1-q4": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "b-u1-q5": {
    "qtype": "mc",
    "answer": "NCBI"
  },
  "b-u2-q1": {
    "qtype": "mc",
    "answer": "polar"
  },
  "b-u2-q2": {
    "qtype": "short",
    "answer": "amino"
  },
  "b-u2-q3": {
    "qtype": "mc",
    "answer": "nucleic acids"
  },
  "b-u2-q4": {
    "qtype": "numeric",
    "answer": 4,
    "tolerance": 0.000001
  },
  "b-u2-q5": {
    "qtype": "mc",
    "answer": "amino-acid sequence"
  },
  "b-u3-q1": {
    "qtype": "mc",
    "answer": "membrane"
  },
  "b-u3-q2": {
    "qtype": "short",
    "answer": "endosymbiotic"
  },
  "b-u3-q3": {
    "qtype": "mc",
    "answer": "rotary motor"
  },
  "b-u3-q4": {
    "qtype": "mc",
    "answer": "a nucleus"
  },
  "b-u3-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "b-u4-q1": {
    "qtype": "mc",
    "answer": "DNA → RNA → protein"
  },
  "b-u4-q2": {
    "qtype": "short",
    "answer": "t"
  },
  "b-u4-q3": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "b-u4-q4": {
    "qtype": "mc",
    "answer": "semi-conservative"
  },
  "b-u4-q5": {
    "qtype": "mc",
    "answer": "NCBI Gene"
  },
  "b-mt-q1": {
    "qtype": "numeric",
    "answer": 4,
    "tolerance": 0.000001
  },
  "b-mt-q2": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "b-mt-q3": {
    "qtype": "short",
    "answer": "t"
  },
  "b-mt-q4": {
    "qtype": "mc",
    "answer": "DNA to RNA to protein"
  },
  "b-mt-q5": {
    "qtype": "short",
    "answer": "amino acids"
  },
  "b-mt-q6": {
    "qtype": "mc",
    "answer": "fluid mosaic"
  },
  "b-mt-q7": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "b-mt-q8": {
    "qtype": "mc",
    "answer": "3"
  },
  "b-u5-q1": {
    "qtype": "numeric",
    "answer": 0.25,
    "tolerance": 0.000001
  },
  "b-u5-q2": {
    "qtype": "short",
    "answer": "alleles"
  },
  "b-u5-q3": {
    "qtype": "mc",
    "answer": "no selection, no drift, no mutation, no migration, random mating"
  },
  "b-u5-q4": {
    "qtype": "numeric",
    "answer": 0.5,
    "tolerance": 0.000001
  },
  "b-u5-q5": {
    "qtype": "mc",
    "answer": "the same chromosome and may hitchhike"
  },
  "b-u6-q1": {
    "qtype": "short",
    "answer": "atp"
  },
  "b-u6-q2": {
    "qtype": "mc",
    "answer": "chemical bonds (sugars etc.)"
  },
  "b-u6-q3": {
    "qtype": "mc",
    "answer": "fuel molecules like glucose"
  },
  "b-u6-q4": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "b-u6-q5": {
    "qtype": "mc",
    "answer": "true"
  },
  "b-u7-q1": {
    "qtype": "mc",
    "answer": "variation, heredity, differential success"
  },
  "b-u7-q2": {
    "qtype": "short",
    "answer": "descendants"
  },
  "b-u7-q3": {
    "qtype": "mc",
    "answer": "relatedness"
  },
  "b-u7-q4": {
    "qtype": "mc",
    "answer": "NCBI Taxonomy"
  },
  "b-u7-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "b-u8-q1": {
    "qtype": "mc",
    "answer": "dN/dt = rN"
  },
  "b-u8-q2": {
    "qtype": "short",
    "answer": "k"
  },
  "b-u8-q3": {
    "qtype": "mc",
    "answer": "decreases at higher trophic levels"
  },
  "b-u8-q4": {
    "qtype": "numeric",
    "answer": 0,
    "tolerance": 0.000001
  },
  "b-u8-q5": {
    "qtype": "mc",
    "answer": "biogeochemical"
  },
  "b-fn-q1": {
    "qtype": "short",
    "answer": "t"
  },
  "b-fn-q2": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "b-fn-q3": {
    "qtype": "numeric",
    "answer": 0.25,
    "tolerance": 0.000001
  },
  "b-fn-q4": {
    "qtype": "short",
    "answer": "atp"
  },
  "b-fn-q5": {
    "qtype": "mc",
    "answer": "true"
  },
  "b-fn-q6": {
    "qtype": "short",
    "answer": "k"
  },
  "b-fn-q7": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "b-fn-q8": {
    "qtype": "mc",
    "answer": "NCBI"
  },
  "v-u1-q1": {
    "qtype": "mc",
    "answer": "force"
  },
  "v-u1-q2": {
    "qtype": "short",
    "answer": "social"
  },
  "v-u1-q3": {
    "qtype": "mc",
    "answer": "ultimate authority in a territory"
  },
  "v-u1-q4": {
    "qtype": "mc",
    "answer": "why people treat power as rightful"
  },
  "v-u1-q5": {
    "qtype": "numeric",
    "answer": 1,
    "tolerance": 0.000001
  },
  "v-u2-q1": {
    "qtype": "mc",
    "answer": "representation and law over raw majority will"
  },
  "v-u2-q2": {
    "qtype": "short",
    "answer": "autocracy"
  },
  "v-u2-q3": {
    "qtype": "mc",
    "answer": "harm minorities"
  },
  "v-u2-q4": {
    "qtype": "mc",
    "answer": "executive power with weak checks"
  },
  "v-u2-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "v-u3-q1": {
    "qtype": "mc",
    "answer": "written in a canonical text"
  },
  "v-u3-q2": {
    "qtype": "short",
    "answer": "5"
  },
  "v-u3-q3": {
    "qtype": "mc",
    "answer": "harder to change than ordinary law"
  },
  "v-u3-q4": {
    "qtype": "numeric",
    "answer": 0.666667,
    "tolerance": 0.01
  },
  "v-u3-q5": {
    "qtype": "mc",
    "answer": "NARA / constitution.congress.gov"
  },
  "v-u4-q1": {
    "qtype": "mc",
    "answer": "legislative, executive, judicial"
  },
  "v-u4-q2": {
    "qtype": "short",
    "answer": "ambition"
  },
  "v-u4-q3": {
    "qtype": "mc",
    "answer": "executive on legislation"
  },
  "v-u4-q4": {
    "qtype": "mc",
    "answer": "statutes and acts’ constitutionality"
  },
  "v-u4-q5": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "v-mt-q1": {
    "qtype": "short",
    "answer": "contract"
  },
  "v-mt-q2": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "v-mt-q3": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "v-mt-q4": {
    "qtype": "short",
    "answer": "ambition"
  },
  "v-mt-q5": {
    "qtype": "mc",
    "answer": "amendment"
  },
  "v-mt-q6": {
    "qtype": "mc",
    "answer": "NARA"
  },
  "v-mt-q7": {
    "qtype": "short",
    "answer": "force"
  },
  "v-mt-q8": {
    "qtype": "numeric",
    "answer": 0.666667,
    "tolerance": 0.01
  },
  "v-u5-q1": {
    "qtype": "mc",
    "answer": "national and subnational governments"
  },
  "v-u5-q2": {
    "qtype": "short",
    "answer": "reserved"
  },
  "v-u5-q3": {
    "qtype": "mc",
    "answer": "listed to the federal government"
  },
  "v-u5-q4": {
    "qtype": "mc",
    "answer": "shared"
  },
  "v-u5-q5": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "v-u6-q1": {
    "qtype": "mc",
    "answer": "introduction, committee, floor, presentment"
  },
  "v-u6-q2": {
    "qtype": "short",
    "answer": "bicameral"
  },
  "v-u6-q3": {
    "qtype": "mc",
    "answer": "congress.gov"
  },
  "v-u6-q4": {
    "qtype": "mc",
    "answer": "a code"
  },
  "v-u6-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "v-u7-q1": {
    "qtype": "mc",
    "answer": "reasoned judgment from short-term politics"
  },
  "v-u7-q2": {
    "qtype": "short",
    "answer": "court"
  },
  "v-u7-q3": {
    "qtype": "mc",
    "answer": "supremecourt.gov"
  },
  "v-u7-q4": {
    "qtype": "mc",
    "answer": "fits the constitution"
  },
  "v-u7-q5": {
    "qtype": "numeric",
    "answer": 9,
    "tolerance": 0.000001
  },
  "v-u8-q1": {
    "qtype": "mc",
    "answer": "freedoms from interference"
  },
  "v-u8-q2": {
    "qtype": "short",
    "answer": "writ"
  },
  "v-u8-q3": {
    "qtype": "mc",
    "answer": "fair procedure (and sometimes substance) before deprivation"
  },
  "v-u8-q4": {
    "qtype": "mc",
    "answer": "NARA"
  },
  "v-u8-q5": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "v-fn-q1": {
    "qtype": "short",
    "answer": "contract"
  },
  "v-fn-q2": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "v-fn-q3": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "v-fn-q4": {
    "qtype": "short",
    "answer": "ambition"
  },
  "v-fn-q5": {
    "qtype": "mc",
    "answer": "amendment"
  },
  "v-fn-q6": {
    "qtype": "short",
    "answer": "reserved"
  },
  "v-fn-q7": {
    "qtype": "mc",
    "answer": "congress.gov"
  },
  "v-fn-q8": {
    "qtype": "numeric",
    "answer": 9,
    "tolerance": 0.000001
  },
  "h-u1-q1": {
    "qtype": "mc",
    "answer": "internal stability against entropic dissipation"
  },
  "h-u1-q2": {
    "qtype": "short",
    "answer": "set"
  },
  "h-u1-q3": {
    "qtype": "mc",
    "answer": "educational inquiry and triage literacy, not direct clinical prescription"
  },
  "h-u1-q4": {
    "qtype": "numeric",
    "answer": 7.4,
    "tolerance": 0.05
  },
  "h-u1-q5": {
    "qtype": "mc",
    "answer": "MedlinePlus and PubMed"
  },
  "h-u2-q1": {
    "qtype": "mc",
    "answer": "bulk convection transport of oxygen, nutrients, hormones, and waste"
  },
  "h-u2-q2": {
    "qtype": "short",
    "answer": "nephron"
  },
  "h-u2-q3": {
    "qtype": "mc",
    "answer": "alveoli"
  },
  "h-u2-q4": {
    "qtype": "numeric",
    "answer": 11,
    "tolerance": 0.000001
  },
  "h-u2-q5": {
    "qtype": "mc",
    "answer": "traveling via bloodstream hormones rather than axonal action potentials"
  },
  "h-u3-q1": {
    "qtype": "mc",
    "answer": "60 to 100 beats per minute"
  },
  "h-u3-q2": {
    "qtype": "short",
    "answer": "diastolic"
  },
  "h-u3-q3": {
    "qtype": "numeric",
    "answer": 20,
    "tolerance": 0.000001
  },
  "h-u3-q4": {
    "qtype": "mc",
    "answer": "95% to 100%"
  },
  "h-u3-q5": {
    "qtype": "mc",
    "answer": "hypothalamus"
  },
  "h-u4-q1": {
    "qtype": "mc",
    "answer": "immediate, non-specific barrier and phagocytic defense"
  },
  "h-u4-q2": {
    "qtype": "short",
    "answer": "antibodies"
  },
  "h-u4-q3": {
    "qtype": "mc",
    "answer": "exposing the immune system to an antigen without causing full virulent disease"
  },
  "h-u4-q4": {
    "qtype": "numeric",
    "answer": 5,
    "tolerance": 0.000001
  },
  "h-u4-q5": {
    "qtype": "mc",
    "answer": "CDC and WHO"
  },
  "h-mt-q1": {
    "qtype": "numeric",
    "answer": 7.4,
    "tolerance": 0.05
  },
  "h-mt-q2": {
    "qtype": "numeric",
    "answer": 11,
    "tolerance": 0.000001
  },
  "h-mt-q3": {
    "qtype": "short",
    "answer": "nephron"
  },
  "h-mt-q4": {
    "qtype": "mc",
    "answer": "alveoli"
  },
  "h-mt-q5": {
    "qtype": "short",
    "answer": "diastolic"
  },
  "h-mt-q6": {
    "qtype": "numeric",
    "answer": 20,
    "tolerance": 0.000001
  },
  "h-mt-q7": {
    "qtype": "mc",
    "answer": "hypothalamus"
  },
  "h-mt-q8": {
    "qtype": "short",
    "answer": "antibodies"
  },
  "h-u5-q1": {
    "qtype": "mc",
    "answer": "C-A-B: Compressions, Airway, Breathing"
  },
  "h-u5-q2": {
    "qtype": "numeric",
    "answer": 100,
    "tolerance": 20
  },
  "h-u5-q3": {
    "qtype": "short",
    "answer": "aed"
  },
  "h-u5-q4": {
    "qtype": "mc",
    "answer": "activate emergency response (911) and begin high-quality chest compressions"
  },
  "h-u5-q5": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "h-u6-q1": {
    "qtype": "mc",
    "answer": "firm, direct pressure and application of an arterial tourniquet proximal to the wound"
  },
  "h-u6-q2": {
    "qtype": "short",
    "answer": "shock"
  },
  "h-u6-q3": {
    "qtype": "mc",
    "answer": "note the exact time of application and never loosen it until surgical care"
  },
  "h-u6-q4": {
    "qtype": "mc",
    "answer": "cool, clean running tap water for 10 to 20 minutes"
  },
  "h-u6-q5": {
    "qtype": "numeric",
    "answer": 3,
    "tolerance": 0.000001
  },
  "h-u7-q1": {
    "qtype": "mc",
    "answer": "intestinal sodium-glucose co-transport (SGLT1) driving passive water absorption"
  },
  "h-u7-q2": {
    "qtype": "short",
    "answer": "potassium"
  },
  "h-u7-q3": {
    "qtype": "numeric",
    "answer": 245,
    "tolerance": 10
  },
  "h-u7-q4": {
    "qtype": "mc",
    "answer": "sunken fontanelle, lack of tears, lethargy, and delayed capillary refill"
  },
  "h-u7-q5": {
    "qtype": "mc",
    "answer": "hypertonic relative to human plasma"
  },
  "h-u8-q1": {
    "qtype": "mc",
    "answer": "systematic reviews and meta-analyses of randomized controlled trials (RCTs)"
  },
  "h-u8-q2": {
    "qtype": "short",
    "answer": "sensitivity"
  },
  "h-u8-q3": {
    "qtype": "mc",
    "answer": "immediate emergency activation (911 / emergency department)"
  },
  "h-u8-q4": {
    "qtype": "numeric",
    "answer": 10,
    "tolerance": 0.000001
  },
  "h-u8-q5": {
    "qtype": "mc",
    "answer": "false: confounding variables and reverse causality must be rigorously ruled out"
  },
  "h-fn-q1": {
    "qtype": "short",
    "answer": "set"
  },
  "h-fn-q2": {
    "qtype": "numeric",
    "answer": 7.4,
    "tolerance": 0.05
  },
  "h-fn-q3": {
    "qtype": "short",
    "answer": "nephron"
  },
  "h-fn-q4": {
    "qtype": "mc",
    "answer": "60 to 100 beats per minute"
  },
  "h-fn-q5": {
    "qtype": "short",
    "answer": "diastolic"
  },
  "h-fn-q6": {
    "qtype": "mc",
    "answer": "C-A-B: Compressions, Airway, Breathing"
  },
  "h-fn-q7": {
    "qtype": "short",
    "answer": "shock"
  },
  "h-fn-q8": {
    "qtype": "short",
    "answer": "1"
  },
  "h-fn-q9": {
    "qtype": "numeric",
    "answer": 2,
    "tolerance": 0.000001
  },
  "h-fn-q10": {
    "qtype": "mc",
    "answer": "systematic reviews and meta-analyses of RCTs"
  }
};
